# Generated by Django 3.1 on 2020-08-29 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TKjv',
            fields=[
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('b', models.IntegerField(blank=True, null=True)),
                ('c', models.IntegerField(blank=True, null=True)),
                ('v', models.IntegerField(blank=True, null=True)),
                ('t', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 't_kjv',
                'managed': False,
            },
        ),
    ]
